#!/usr/bin/env bash
# Transfers a file from local to remote
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [ $# -lt 3 ]; then
    echo ATH_TO_SSH_KEY'
elif [ "$#" -eq 3 ]
then
    scp -'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME Po StrictHostKeyChecking=no $PATH_TO_FILE "$USERNAME@$IP:~/"
else
    scp -o StrictHostKeyChecking=no -i $PATH_TO_SSH_KEY $PATH_TO_FILE "$USERNAME@$IP:~/"
fi
